//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boekhouden
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factuur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factuur()
        {
            this.FactuurRegels = new HashSet<Factuurregel>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RelatieId { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string FactuurNummer { get; set; }
        public Nullable<System.Guid> KostenplaatsId { get; set; }
        public Nullable<System.Guid> RekeningId { get; set; }
        public Nullable<bool> Betaald { get; set; }
        public Nullable<System.DateTime> BetaalDatum { get; set; }
        public string Toelichting { get; set; }
        public Nullable<System.Guid> FactuurTypeId { get; set; }
        public System.Guid TenantId { get; set; }
        public System.Guid BoekhoudingId { get; set; }
    
        public virtual FactuurType FactuurType { get; set; }
        public virtual Kostenplaats Kostenplaats { get; set; }
        public virtual Rekening Rekening { get; set; }
        public virtual Relatie Relatie { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factuurregel> FactuurRegels { get; set; }
        public virtual Boekhouding Boekhouding { get; set; }
    }
}
