//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boekhouden
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kostenplaats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kostenplaats()
        {
            this.Factuur = new HashSet<Factuur>();
        }
    
        public System.Guid Id { get; set; }
        public string Naam { get; set; }
        public int Volgnummer { get; set; }
        public bool Actief { get; set; }
        public System.Guid BoekhoudingId { get; set; }
        public System.Guid TenantId { get; set; }
    
        public virtual Boekhouding Boekhouding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factuur> Factuur { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
