//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boekhouden
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Boekhouding> Boekhoudingen { get; set; }
        public virtual DbSet<BTWType> BTWTypes { get; set; }
        public virtual DbSet<Land> Landen { get; set; }
        public virtual DbSet<Relatie> Relaties { get; set; }
        public virtual DbSet<RelatieType> RelatieTypes { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<Factuur> Facturen { get; set; }
        public virtual DbSet<Factuurregel> Factuurregels { get; set; }
        public virtual DbSet<FactuurType> tblFactuurType_fty { get; set; }
        public virtual DbSet<Kostenplaats> Kostenplaatsen { get; set; }
        public virtual DbSet<Productsoort> Productsoorten { get; set; }
        public virtual DbSet<Rekening> Rekeningen { get; set; }
    }
}
