//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boekhouden
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatie
    {
        public System.Guid Id { get; set; }
        public System.Guid BoekhoudingId { get; set; }
        public long RelatieTypeId { get; set; }
        public string Naam1 { get; set; }
        public string Naam2 { get; set; }
        public string Contactpersoon { get; set; }
        public string Aanhef { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string Postcode { get; set; }
        public string LandId { get; set; }
        public string LandNaam { get; set; }
        public string Plaats { get; set; }
        public string BTWNr { get; set; }
        public string Telefoon { get; set; }
        public string Email { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> BTWId { get; set; }
        public string Kenmerk { get; set; }
        public System.Guid TenantId { get; set; }
    
        public virtual Boekhouding Boekhouding { get; set; }
        public virtual BTWType BTW { get; set; }
        public virtual Land Land { get; set; }
        public virtual RelatieType RelatieType { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
