CREATE TABLE [dbo].[tblRelatie_rel] (
    [relId]             UNIQUEIDENTIFIER NOT NULL,
    [rel_tenId]         UNIQUEIDENTIFIER NOT NULL,
    [rel_bhoId]         UNIQUEIDENTIFIER NOT NULL,
    [rel_rtyId]         BIGINT           NOT NULL, 
    [relName1]          NVARCHAR (128)   NOT NULL,
    [relName2]          NVARCHAR (128)   NULL, 
    [relContactpersoon] NVARCHAR (128)   NULL,
    [relAanhef]         NVARCHAR (128)   NULL,
    [relAdres1]         NVARCHAR (128)   NULL,
    [relAdres2]         NVARCHAR (128)   NULL,
    [relPostcode]       NVARCHAR (128)   NULL,
    [rel_lanId]         NVARCHAR (2)     NULL,
    [relLandnaam]       NVARCHAR (128)   NULL,
    [relPlaats]         NVARCHAR (128)   NULL,
    [relBTWNr]          NVARCHAR (128)   NULL,
    [relTelefoon]       NVARCHAR (128)   NULL,
    [relEmail]          NVARCHAR (128)   NULL,
    [relIBAN]           NVARCHAR (128)   NULL,
    [rel_btwId]         INT              NULL,
    [relKenmerk]        NVARCHAR (128)   NULL,
    PRIMARY KEY CLUSTERED ([relId] ASC),
    CONSTRAINT [FK_tblRelatie_tblTenant_id] FOREIGN KEY ([rel_tenId]) REFERENCES [dbo].[tblTenant_ten] ([tenId]),
    CONSTRAINT [FK_tblRelatie_tblRelatieType_id] FOREIGN KEY ([rel_rtyId]) REFERENCES [dbo].[tblRelatieType_rty] ([rtyId]) ON DELETE CASCADE,
    CONSTRAINT [FK_tblRelatie_tblLand_id] FOREIGN KEY ([rel_lanId]) REFERENCES [dbo].[tblLand_lan] ([lanId]) ON DELETE CASCADE,
    CONSTRAINT [FK_tblRelatie_tblBTW_id] FOREIGN KEY ([rel_btwId]) REFERENCES [dbo].[tblBTW_btw] ([btwId]) ON DELETE CASCADE,
    CONSTRAINT [FK_tblRelatie_tblBoekhouding_id] FOREIGN KEY ([rel_bhoId]) REFERENCES [dbo].[tblBoekhouding_bho] ([bhoId]) ON DELETE CASCADE
);

